development: &default
adapter: postgresql
database: gigi_development
encoding: utf8
min_messages: warning
pool: 5
timeout: 5000
host: localhost
port: 5432
username: gigi
password: gigi

test:
  <<: *default
  database: gigi_test

production:
  <<: *default
  database: gigi_production 

staging:
  <<: *default
  database: gigi_staging   